### ISSUE TITLE
Error on launch (1.1.0)

### ISSUE THREAD

**Issue by Dovahkick** [Extegral/Enigmatic-Legacy#1]
This is the error log I'm getting as of 1.1.0:

**[02sept.2019 12:58:44.792] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, The_Dovahkick, --version, 1.14.4-forge-28.0.45, --gameDir, C:\Users\ncauv\AppData\Roaming\.minecraft, --assetsDir, C:\Users\ncauv\AppData\Roaming\.minecraft\assets, --assetIndex, 1.14, --uuid, 559a7ee6ec384d31b03c3ebee00af14d, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.0.45, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190719.225934]
[02sept.2019 12:58:44.794] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 3.2.0+60+b86c1d4 starting: java version 1.8.0_51 by Oracle Corporation
[02sept.2019 12:58:46.022] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[02sept.2019 12:58:46.667] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.14.4-forge-28.0.45, --gameDir, C:\Users\ncauv\AppData\Roaming\.minecraft, --assetsDir, C:\Users\ncauv\AppData\Roaming\.minecraft\assets, --username, The_Dovahkick, --assetIndex, 1.14, --uuid, 559a7ee6ec384d31b03c3ebee00af14d, --accessToken, ????????, --userType, mojang, --versionType, release]
[02sept.2019 12:58:47.730] [Client thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: The_Dovahkick
[02sept.2019 12:58:52.095] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: lastServer:
[02sept.2019 12:58:52.113] [Client thread/INFO] [net.minecraft.client.Minecraft/]: LWJGL Version: 3.2.2 build 10
[02sept.2019 12:58:53.258] [modloading-worker-11/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 28.0.45, for MC 1.14.4 with MCP 20190719.225934
[02sept.2019 12:58:53.258] [modloading-worker-11/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v28.0.45 Initialized
[02sept.2019 12:58:53.323] [modloading-worker-4/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: enigmaticlegacy, class com.integral.enigmaticlegacy.EnigmaticLegacy
java.lang.NoClassDefFoundError: net/minecraftforge/common/crafting/conditions/IConditionSerializer
	at com.integral.enigmaticlegacy.EnigmaticLegacy.<init>(EnigmaticLegacy.java:163) ~[?:1.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:28.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2022/404787971.accept(Unknown Source) [?:28.0]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2021/300836639.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2021/300836639.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:133) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2073/1283367290.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.crafting.conditions.IConditionSerializer
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102) ~[modlauncher-3.2.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 24 more
[02sept.2019 12:58:53.380] [Client thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[02sept.2019 12:58:53.380] [Client thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-0.10.6-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1977/1555728654.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:79) [?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:453) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.45.jar:28.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$341/1617156106.call(Unknown Source) [forge-1.14.4-28.0.45.jar:28.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?]
[02sept.2019 12:58:54.358] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[02sept.2019 12:58:55.068] [Server-Worker-6/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[02sept.2019 12:58:55.069] [Server-Worker-6/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[02sept.2019 12:58:55.069] [Server-Worker-6/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-0.10.6-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1977/1555728654.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:105) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:87) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2321/2088048274.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1977/1555728654.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[02sept.2019 12:58:56.381] [Server-Worker-4/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[02sept.2019 12:58:56.381] [Server-Worker-4/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[02sept.2019 12:58:56.381] [Server-Worker-4/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-0.10.6-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1977/1555728654.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:118) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:89) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2323/1894767896.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[02sept.2019 12:58:56.385] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: lastServer:
[02sept.2019 12:58:56.598] [Client thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[02sept.2019 12:58:56.598] [Client thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[02sept.2019 12:58:56.706] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512 textures-atlas
[02sept.2019 12:58:57.068] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/particle-atlas
[02sept.2019 12:58:57.069] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/painting-atlas
[02sept.2019 12:58:57.069] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128 textures/mob_effect-atlas
[02sept.2019 12:58:57.085] [Client thread/ERROR] [net.minecraftforge.fml.ForgeI18n/CORE]: Illegal format found `{0,modinfo,name} ({0,modinfo,id}) n'a pas été chargé correctement
{2,exc,msg}`
[02sept.2019 12:58:57.086] [Client thread/ERROR] [net.minecraftforge.fml.ForgeI18n/CORE]: Illegal format found `{0,modinfo,name} ({0,modinfo,id}) n'a pas été chargé correctement
{2,exc,msg}`**

**Comment by Extegral** [comment]
Try to update forge to at 28.0.75 (or later) and report whether error persists.

**Comment by Dovahkick** [comment]
The error doesn't appear anymore, it's fixed.
