### ISSUE TITLE
Kicked after putting an amulet on

### ISSUE THREAD

**Issue by Nick7263** [Extegral/Enigmatic-Legacy#108]
So i put Pearl of the void in my amulet slot and i got kicked with(Internal server error)

Console:
[INFO] .... [minecraft/DedicatedServer]: Matariel joined the game

[INFO] .... [Enigmatic Legacy/]: Synchronizing omniconfig files to Matariel...

[INFO] .... [Enigmatic Legacy/]: Sending data for enigmaticlegacy-common.omniconf

[ERROR] .... [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@243e9a4 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!

[ERROR] .... [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@5527146e (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!

[ERROR] .... [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null

Index: 5

Listeners:

0: NORMAL

1: ASM: class tfar.randomenchants.ench.enchantment.EnchantmentQuickdraw onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

2: ASM: com.legacy.leap.LeapEntityEvents@cb0be7f onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

3: ASM: class com.stal111.forbidden_arcanus.event.PlayerTickListener onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

4: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@256780fe onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

5: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@204956e6 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

6: ASM: shetiphian.terraqueous.common.misc.EventHandler@620015a3 livingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

java.util.ConcurrentModificationException

at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)

at java.util.HashMap$ValueIterator.next(HashMap.java:1474)

at com.integral.enigmaticlegacy.items.VoidPearl.curioTick(VoidPearl.java:176)

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$null$17(CuriosEventHandler.java:370)

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$tick$23(CuriosEventHandler.java:370)

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)

at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:351)

at net.minecraftforge.eventbus.ASMEventHandler_258_CuriosEventHandler_tick_LivingUpdateEvent.invoke(.dynamic)

at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)

at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310)

at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112)

at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)

at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400)

at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195)

at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227)

at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861)

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283)

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)

at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638)

at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229)

at java.lang.Thread.run(Thread.java:748)

.... [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 753fb909-7d39-4d36-86e5-4a2d9f2e4428

[WARNING] .... [minecraft/NetworkSystem]: Failed to handle packet for /62.228.7.35:58252

net.minecraft.crash.ReportedException: Ticking player

at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:463) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}

at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}

at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}

at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

Caused by: java.util.ConcurrentModificationException

at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212] {}

at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_212] {}

at com.integral.enigmaticlegacy.items.VoidPearl.curioTick(VoidPearl.java:176) ~[enigmaticlegacy:2.0] {re:classloading,pl:runtimedistcleaner:A}

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$null$17(CuriosEventHandler.java:370) ~[curios:property(class java.lang.String, map(provider(?)))] {re:classloading}

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[forge:?] {re:classloading}

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$tick$23(CuriosEventHandler.java:370) ~[curios:property(class java.lang.String, map(provider(?)))] {re:classloading}

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[forge:?] {re:classloading}

at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:351) ~[curios:property(class java.lang.String, map(provider(?)))] {re:classloading}

at net.minecraftforge.eventbus.ASMEventHandler_258_CuriosEventHandler_tick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}

at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}

at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[forge:?] {re:classloading}

at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}

at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}

... 9 more

[ERROR] .... [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null

Index: 5

Listeners:

0: NORMAL

1: ASM: class tfar.randomenchants.ench.enchantment.EnchantmentQuickdraw onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

2: ASM: com.legacy.leap.LeapEntityEvents@cb0be7f onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

3: ASM: class com.stal111.forbidden_arcanus.event.PlayerTickListener onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

4: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@256780fe onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

5: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@204956e6 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

6: ASM: shetiphian.terraqueous.common.misc.EventHandler@620015a3 livingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V

java.util.ConcurrentModificationException

at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)

at java.util.HashMap$ValueIterator.next(HashMap.java:1474)

at com.integral.enigmaticlegacy.items.VoidPearl.curioTick(VoidPearl.java:176)

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$null$17(CuriosEventHandler.java:370)

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$tick$23(CuriosEventHandler.java:370)

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)

at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:351)

at net.minecraftforge.eventbus.ASMEventHandler_258_CuriosEventHandler_tick_LivingUpdateEvent.invoke(.dynamic)

at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)

at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310)

at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112)

at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)

at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400)

at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195)

at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227)

at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861)

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283)

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)

at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638)

at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229)

at java.lang.Thread.run(Thread.java:748)

.... [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID fa251856-0c64-4a01-9db7-3420d22e7af4

[WARNING] .... [minecraft/NetworkSystem]: Failed to handle packet for /62.228.7.35:58252

net.minecraft.crash.ReportedException: Ticking player

at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:463) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}

at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}

at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}

at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

Caused by: java.util.ConcurrentModificationException

at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212] {}

at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_212] {}

at com.integral.enigmaticlegacy.items.VoidPearl.curioTick(VoidPearl.java:176) ~[enigmaticlegacy:2.0] {re:classloading,pl:runtimedistcleaner:A}

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$null$17(CuriosEventHandler.java:370) ~[curios:property(class java.lang.String, map(provider(?)))] {re:classloading}

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[forge:?] {re:classloading}

at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$tick$23(CuriosEventHandler.java:370) ~[curios:property(class java.lang.String, map(provider(?)))] {re:classloading}

at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[forge:?] {re:classloading}

at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:351) ~[curios:property(class java.lang.String, map(provider(?)))] {re:classloading}

at net.minecraftforge.eventbus.ASMEventHandler_258_CuriosEventHandler_tick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}

at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}

at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[forge:?] {re:classloading}

at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}

at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}

... 9 more

[INFO] .... [minecraft/ServerPlayNetHandler]: Matariel lost connection: Internal server error

[INFO] .... [minecraft/DedicatedServer]: Matariel left the game

**Comment by Nick7263** [comment]
Happens every time i join

**Comment by Aizistral** [comment]
Please create your issue again using bug report template: [Click Here](https://github.com/Extegral/Enigmatic-Legacy/issues/new?assignees=Extegral&labels=bug%2C+awaits+review&template=bug-report.md&title=)
...and this time don't erase everything you're supposed to fill in, pretending that it wasn't there. Don't question, it's all important.
