### ISSUE TITLE
1.16.5 Crash server on startup

### ISSUE THREAD

**Issue by ghost** [Extegral/Enigmatic-Legacy#184]
Hi, i add crash log down.
Forge-1.16.5-36.1.16
EnigmaticLegacy-2.11.3
-- Head --
Thread: main
Stacktrace:
        at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_291] {}
-- MOD enigmaticlegacy --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
                at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_291] {}
                at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_291] {}
                at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_291] {}
                at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_291] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.register(EventBus.java:256) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.lambda$null$6(EventBus.java:98) ~[eventbus-4.0.0.jar:?] {}
                at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_291] {}
                at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:98) ~[eventbus-4.0.0.jar:?] {}
                at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_291] {}
                at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-4.0.0.jar:?] {}
                at com.integral.enigmaticlegacy.EnigmaticLegacy.<init>(EnigmaticLegacy.java:557) ~[enigmaticlegacy:2.11.3] {re:mixin,pl:object_holder_definalize:A,pl:runtimedistcleaner:A,re:classloading,pl:object_holder_definalize:A,pl:runtimedistcleaner:A}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_291] {}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291] {}
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291] {}
                at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_291] {}
                at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_291] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

        Mod File: EnigmaticLegacy-2.11.3.jar
        Failure message: Enigmatic Legacy (enigmaticlegacy) has failed to load correctly
                java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
        Mod Version: 2.11.2
        Mod Issue URL: https://github.com/Extegral/Enigmatic-Legacy/issues
        Exception message: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
Stacktrace:
        at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_291] {}
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_291] {}
        at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.register(EventBus.java:256) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$null$6(EventBus.java:98) ~[eventbus-4.0.0.jar:?] {}
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_291] {}
        at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:98) ~[eventbus-4.0.0.jar:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_291] {}
        at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-4.0.0.jar:?] {}
        at com.integral.enigmaticlegacy.EnigmaticLegacy.<init>(EnigmaticLegacy.java:557) ~[enigmaticlegacy:2.11.3] {re:mixin,pl:object_holder_definalize:A,pl:runtimedistcleaner:A,re:classloading,pl:object_holder_definalize:A,pl:runtimedistcleaner:A}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_291] {}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

**Comment by Yourname942** [comment]
I am also getting this error with the new update:
crash log:
https://gist.github.com/Yourname942/49fe9718b1cacced716c45262ab32c6d
server latest log:
https://gist.github.com/Yourname942/72536372d898138fbd50d7a6f774cbd9
server debug log:
https://gist.github.com/Yourname942/05a4106b376aab0fded306445c78e2ac

**Comment by Divineaspect** [comment]
crash log:
https://pastebin.com/5Q8W6bVE

**Comment by Aizistral** [comment]
@Senyum, be aware that any submitted bug reports that disregard bug report template will not be reviewed.

The crash should be fixed in 2.11.4, however.
