### ISSUE TITLE
Server Crash on Start: Modules etherium and enigmaticlegacy export package com.integral.enigmaticlegacy.helpers to module sit

### ISSUE THREAD

**Issue by EchoWhiskeyZero** [Extegral/Enigmatic-Legacy#250]
Hello, 
I am trying to start up a forge server (forge-1.18.1-39.0.59-universal.jar) on an Ubuntu server with JDK17 and get this error when I try to start the forge server. Any ideas?

**My mod files:**

- curios-forge-1.18.1-5.0.5.2.jar
- EnigmaticLegacy-2.13.2.jar
- Etherium-FORGE-1.18.1-v1.2.0.jar
- Patchouli-1.18.1-64.jar

**Startup Error:**
```
[18:22:55] [main/INFO]: Found mod file forge-1.18.1-39.0.59-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5dda6f9
Exception in thread "main" java.lang.module.ResolutionException: Modules etherium and enigmaticlegacy export package com.integral.enigmaticlegacy.helpers to module sit
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

```

**Comment by Aizistral** [comment]
Why do you have both Etherium and Enigmatic Legacy installed? You're supposed to pick one you know

**Comment by EchoWhiskeyZero** [comment]
Ah, sorry....I was getting another error and thought I saw it was a dependency. Let me remove it and get the original error message

**Comment by EchoWhiskeyZero** [comment]
Let me know if you want me to create a separate issue. This is the error with Etherium removed.

```Crash Report UUID: aa4ec6bb-ce68-47de-a408-bb1cb04b6716
        FML: 39.0
        Forge: net.minecraftforge:39.0.59[19:51:07] [main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Enigmatic Legacy (enigmaticlegacy) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) ~[fmlcore-1.18.1-39.0.59.jar%2377!/:?]
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.59.jar%2377!/:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.59.jar%2377!/:?]
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[fmlcore-1.18.1-39.0.59.jar%2377!/:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:177) ~[fmlcore-1.18.1-39.0.59.jar%2377!/:?]
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:46) ~[forge-1.18.1-39.0.59-universal.jar%2380!/:?]
        at net.minecraft.server.Main.main(Main.java:104) ~[server-1.18.1-20211210.034407-srg.jar%2376!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]```

**Comment by Aizistral** [comment]
Yes, it would be nice of you to create a separate issue. I would also ask that you use a proper bug report template for it and provide full log according to how it asks you.

**Comment by EchoWhiskeyZero** [comment]
Will do, didn't see a bug report form/template but will look for it. Thank you for the quick response!

**Comment by Aizistral** [comment]
There it is, right after clicking "New issue":
![image](https://user-images.githubusercontent.com/47505981/150706407-2b16150d-3533-4295-ba0b-5e7e9763fd5f.png)
