### ISSUE TITLE
Kicked from server when entering the Nether

### ISSUE THREAD

**Issue by MaxWasUnavailable** [Extegral/Enigmatic-Legacy#335]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.21.1
 * Curios API: 1.18.2-5.0.7.0
 * Patchouli: 1.18.2-67
 * Forge: 40.1.22

#### Description of a Bug:
Players get kicked from a dedicated server when they enter the Nether.

#### How to Reproduce:
1. Walk through Nether Portal
2. Crash

#### Logs:

```
java.lang.NullPointerException: Cannot invoke "com.integral.enigmaticlegacy.objects.TransientPlayerData.getPlayer()" because "msg.playerData" is null
	at com.integral.enigmaticlegacy.packets.clients.PacketSyncTransientData.lambda$handle$0(PacketSyncTransientData.java:33) ~[EnigmaticLegacy-2.21.1.jar%23144!/:2.21.1]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:208) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at com.integral.enigmaticlegacy.packets.clients.PacketSyncTransientData.handle(PacketSyncTransientData.java:28) ~[EnigmaticLegacy-2.21.1.jar%23144!/:2.21.1]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:68) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:75) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:75) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1824) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1013) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.22.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by MaxWasUnavailable** [comment]
It seems this might have something to do with the death crystal that spawns when a player dies?

We recreated the Nether, and it was all fine until a player died in there.

EDIT:

Correction; It was fine until a player died *or* left & went back into the Nether. Dying is not a requirement. So it's probably not the death crystal.

**Comment by StygianNights** [comment]
Cannot investigate right now, but what other mods or information do you have installed? Or is it just Enigmatic Legacy and dependancies?

**Comment by MaxWasUnavailable** [comment]
> Cannot investigate right now, but what other mods or information do you have installed? Or is it just Enigmatic Legacy and dependancies?

Here is a Pastebin taken from an unrelated crash report.

Should list all mods & versions.

Please let me know if I can supply anything else to help!

https://pastebin.com/qqrm08br

**Comment by Noxalas** [comment]
While we don't get kicked out in my server, I get the same crash in the logs. 
Happens on death, and in my case the most noticable thing is that it makes the client forget it's origin (from the Origins mod).

**Comment by StygianNights** [comment]
@Noxalas @MaxWasUnavailable Are you two discussing the same server, or is this two different instances of the same bug? 

If this is an easily findable modpack, I would appreciate the name of it so I don't have to spend 30 minutes finding and installing mods, lol.

**Comment by StygianNights** [comment]
Also is it just the Nether, or does this happen to any other, or all dimensions?

**Comment by StygianNights** [comment]
Also, if you could force reperform the crashing action, and provide me the entire crashlog, not an edited down version. I have a couple of leads.

**Comment by MaxWasUnavailable** [comment]
> @Noxalas @MaxWasUnavailable Are you two discussing the same server, or is this two different instances of the same bug?
> 
> If this is an easily findable modpack, I would appreciate the name of it so I don't have to spend 30 minutes finding and installing mods, lol.

Different servers.

The modpack is a curseforge import, so it's not publicly published. Toss me a message on Discord and I'll send it your way: Max#0007

**Comment by MaxWasUnavailable** [comment]
> Also is it just the Nether, or does this happen to any other, or all dimensions?

We haven't tested The End yet in our server. But the Nether consistently kicks people out as soon as anyone has first entered and left (or died inside of) it. Deleting and regenerating it allows a single person to go back in and play around with things.

Curiously enough; Running the modpack in singleplayer and opening to LAN doesn't cause this issue to occur. So I'm wondering if there's something peculiar about our server / overworld that's causing it?

**Comment by DaComputerNerd717** [comment]
I'm one of the players on Max's server, and can confirm the End worked fine.

**Comment by Rat-CK** [comment]
Also can confirm that the End works completely fine, Just not the nether.
