### ISSUE TITLE
Enigmatic lockbox Book broken [1.18.2]?

### ISSUE THREAD

**Issue by itsdinkd** [Extegral/Enigmatic-Legacy#392]
Latest version on 1.18.2

```java
[01Oct2022 11:21:11.598] [Worker-Main-8/ERROR] [patchouli/]: Failed to load book enigmaticlockbox:extended_acknowledgment defined by mod enigmaticlockbox, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[client-1.18.2-20220404.173914-srg.jar%23421!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23307!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23307!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23307!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23307!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23307!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1332_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23423!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23422!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by Aizistral** [comment]
Fixed by 095e27b67e0607e3d8293dea2d093587436dbd5b.
