### ISSUE TITLE
Incompatibility with Roughly Enough Resources

### ISSUE THREAD

**Issue by seanxiecn** [Extegral/Enigmatic-Legacy#396]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.26.1
 * Curios API: 5.1.1.0
 * Patchouli: 1.19.2-77
 * Forge: 43.1.52
 * Roughly Enough Items: 9.1.572
 * Roughly Enough Resources: 2.6.1

#### Description of a Bug:
Game crashes when entering existing world or creating a new one when both Enigmatic Legacy and Roughly Enough Resources (with respective dependencies) are installed.

#### How to Reproduce:
1. Install both Enigmatic Legacy and Roughly Enough Resources;
2. Enter any world;
3. Behold!

#### Logs:
```
[10:49:05] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
com.google.gson.JsonSyntaxException: Unknown type: com.aizistral.enigmaticlegacy.handlers.LootFunctionRevelation@3f422252
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:120) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2394!/:?] {}
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_7219_(LootPoolSingletonContainer.java:141) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:40) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:80) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:74) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2394!/:?] {}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:187) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2394!/:?] {}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:279) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:253) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2394!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53) ~[rer-2.6.1.jar%23207!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.players.PlayerList.handler$zfo000$onPlayerConnect(PlayerList.java:952) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:247) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:connection.ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:connection.ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:connection.ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,re:classloading,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinClientConnection,pl:mixin:APP:badpackets.mixins.json:MixinConnection,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Comment by Aizistral** [comment]
From stacktrace it is an obvious conflict with Roughly Enough Resources. ~~Please specify what version of that mod you use.~~
Whatever, I guess I figured it all out by myself.
