### ISSUE TITLE
Ticking Memory Connection crash on world creation (w/ other mods)

### ISSUE THREAD

**Issue by Partonetrain** [Extegral/Enigmatic-Legacy#5]
**Does not occur with just Forge/Curious/Enigmatic Legacy**
However, the only mod mentioned in the stacktrace is Enigmatic Legacy. The typical method of pack debugging (splitting mods until you find the one that was the issue) has yet to wield the same crash, so I'm not sure what to do other than open an issue.

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.2.2
 * Curios API: 1.0
 * Forge: 28.1.8

#### Description of a Bug:
Game freezes at 100% on world creation. 

#### How to Reproduce:
1. Create new world (with my modpack specifically?)
2. Wait
3. Get stuck at 100%

#### Logs:
stacktrace:
`
-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:323)
	at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:316)
	at com.integral.enigmaticlegacy.handlers.SuperpositionHandler.hasAdvancement(SuperpositionHandler.java:613)
	at com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler.onPlayerJoin(EnigmaticEventHandler.java:711)
	at net.minecraftforge.eventbus.ASMEventHandler_201_EnigmaticEventHandler_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:43)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:205)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224)
`

full log:
(have to use file, log is too long for pastebin)

[latest.log](https://github.com/Extegral/Enigmatic-Legacy/files/3624025/latest.log)

**Comment by Extegral** [comment]
This should be fixed easily by adding in null check. I am not sure what mod could even cause null to be passed somewhere while checking the player's advancements, though.

**Comment by Partonetrain** [comment]
Somehow, I narrowed it down. I have a data pack loading via [GlobalDataPacks](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack). My data pack doesn't touch advancements, but removing it prevents the crash. _Something_ in my data pack is causing this

This explains why me testing in the other instances with half the modpack didn't do anything, the datapack wasn't there. My data pack is kind of large, but I will take it apart and see what part of it makes the crash reproducible

**Comment by Partonetrain** [comment]
The culprit was this recipe:
`{
    "type": "crafting_shapeless",
    "ingredients": [
        {
            "item": "minecraft:rotten_flesh"
        },
		{
            "item": "minecraft:rotten_flesh"
        },
		{
            "item": "minecraft:rotten_flesh"
        },
		{
			"item": "minecraft:rotten_flesh"
		}
    ],
    "result": {
        "item": "silentgems:biomesoplenty:flesh",
		"count": 1
    }
}`
I accidentally put two namespaces in the output. Fixing this file prevents the crash.
All that said, I have no idea how it crashed with your mod in the stacktrace or what it had to do with advancements.

Thanks for baring with me for a problem that wasn't yours :P

**Comment by Extegral** [comment]
Error in loading that broken thing from your data pack may have caused a deeper error that thrown an exception before warn about failing to parse .json was logged (which should normally happen). I will still make some changes to ensure that if anyone else runs into such problem, it won't take them forever to figure it out.
