### ISSUE TITLE
Internet request will freeze the game for up to 40 seconds at startup

### ISSUE THREAD

**Issue by LTCatt** [Extegral/Enigmatic-Legacy#528]
#### Versions:
 * Enigmatic Legacy: 2.30.1

#### Description of a Bug:
If there's a connection problem, the game will freeze in the red forge loading screen for 40 secs.

debug.log:
```
[289��2024 01:36:04.204] [Worker-ResourceReload-26/DEBUG] [mixin/]: modernfix-forge.mixins.json:perf.kubejs.RecipeEventJSMixin from mod modernfix->@Inject::clearRecipeLists(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V has 0 override(s) in child classes
[289��2024 01:36:04.204] [Worker-ResourceReload-26/DEBUG] [mixin/]: modernfix-forge.mixins.json:perf.kubejs.RecipeEventJSMixin from mod modernfix->@Inject::clearRecipeLists(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V won't be passed a CallbackInfo as a result
[289��2024 01:36:46.117] [Worker-ResourceReload-27/ERROR] [Enigmatic Legacy/ERROR]: Encountered exception when trying to fetch devoted believers from Enigmatic Legacy's repository:
[289��2024 01:36:46.117] [Worker-ResourceReload-27/ERROR] [Enigmatic Legacy/CATCHING]: Catching
java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:533) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:638) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at java.net.URL.openStream(URL.java:1161) ~[?:?]
	at com.aizistral.enigmaticlegacy.handlers.DevotedBelieversHandler.fetchDevotedBelievers(DevotedBelieversHandler.java:136) ~[��������-EnigmaticLegacy-2.30.1.jar%23465!/:2.30.1]
	at com.aizistral.enigmaticlegacy.handlers.DevotedBelieversHandler.loadDevotedBelievers(DevotedBelieversHandler.java:43) ~[��������-EnigmaticLegacy-2.30.1.jar%23465!/:2.30.1]
	at com.aizistral.enigmaticlegacy.handlers.DevotedBelieversHandler.<clinit>(DevotedBelieversHandler.java:27) ~[��������-EnigmaticLegacy-2.30.1.jar%23465!/:2.30.1]
	at com.aizistral.enigmaticlegacy.EnigmaticLegacy.onLoadComplete(EnigmaticLegacy.java:324) ~[��������-EnigmaticLegacy-2.30.1.jar%23465!/:2.30.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.23.jar%23482!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.2.23.jar%23481!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[289��2024 01:36:46.119] [Worker-ResourceReload-27/INFO] [Enigmatic Legacy/INFO]: Will try to restore the list from local backup...
[289��2024 01:36:46.124] [Worker-ResourceReload-27/INFO] [Enigmatic Legacy/INFO]: Successfully restored the list from local backup.
[289��2024 01:36:46.124] [Worker-ResourceReload-27/INFO] [Enigmatic Legacy/]: Believer: ObsidianFlight, UUID: 0cf25168-1b5a-4ac9-90eb-45bb20b0afab
[289��2024 01:36:46.124] [Worker-ResourceReload-27/INFO] [Enigmatic Legacy/]: Believer: Alexsist, UUID: b77d12d4-627f-47d3-965a-74e4f41854cc
```

![%DK OWK@4FZTPL6O6L{W8%R](https://github.com/user-attachments/assets/78930cee-c888-4750-b061-94d06e995545)

**Comment by Tristan-Eternis** [comment]
this looks like an issue with kubejs and modernfix - you should remove all mods before reporting a bug

**Comment by cold233** [comment]
Encountered the same issue. If the game can add a config to disable this would be great.
