### ISSUE TITLE
[1.14.4] Crash when loading game with forge 28.1.39

### ISSUE THREAD

**Issue by Gbergz** [Extegral/Enigmatic-Legacy#7]
#### Versions:
 * Enigmatic Legacy: 1.3.3
 * Curios API: 1.0.2
 * Forge: 28.1.39

#### Description of a Bug:
Installing Forge 28.1.39 makes the game not boot with the mod installed. Forge 28.1.20 worked fine.

#### How to Reproduce:
1. Install Forge 28.1.39
2. Start the game
3. Wait a little bit
...
n. Crash

#### Logs:
I tried uploading it, the site just froze.

#### Note:
28.1.20 worked fine.
also, : 
I'm using many other mods along side this.
It works in a new instance with only Curious & EngimaticLegacy installed.

Crash Log: [GistGithub](https://gist.github.com/Gbergz/c857dae417157f7effbe589bac97c6ec).

**Comment by Extegral** [comment]
It would appear to be good-old NullPointerException, but I have no idea what's causing it. Something passed within into ColorHandlerEvent handler ends up as null, but that should not be possible under any circumstances.

I won't be able to fix this if I cannot reproduce it. Your exceptionally huge mod list could really complicate finding out the origin of the bug. Use classical method of debugging by splitting the modpack until you find the mod that is causing the issue, and report which one it is.

**Comment by Extegral** [comment]
Seems that this issue is caused by some other mod crashing during the load. I found out similar cases, like in gigaherz/ConfigurableReeds#4.

According to that, you will need to check out the latest.log file to see what the crash is actually caused by, or somehow upload it so I can take I a look. Try using different sites, at least some should work.

**Comment by Gbergz** [comment]
Here's the log file as i've just tried updating forge & it still won't boot.

Latest.log: [GistGithub Paste](https://gist.github.com/Gbergz/819c1fde2b3d86adf767cea0072bf40d)

Also a new crash report if you're interested: [GistGithub Paste](https://gist.github.com/Gbergz/d5434c18130636839a60d037de25d25f)

**Comment by Extegral** [comment]
There is an error thrown by Forbidden Arcanus:

```
...
[12:50:13] [Client thread/ERROR]: Exception caught during firing event: net.minecraft.block.FlowerPotBlock.<init>(Lnet/minecraft/block/FlowerPotBlock;Lnet/minecraft/block/Block;Lnet/minecraft/block/Block$Properties;)V
	Index: 6
	Listeners:
		0: NORMAL
		1: ASM: class com.stal111.forbidden_arcanus.potion.ModPotions register(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class com.stal111.forbidden_arcanus.potion.effect.ModEffects register(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class com.stal111.forbidden_arcanus.Main registerEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class com.stal111.forbidden_arcanus.Main registerTileEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class com.stal111.forbidden_arcanus.Main registerSounds(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		6: ASM: class com.stal111.forbidden_arcanus.Main registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		7: ASM: class com.stal111.forbidden_arcanus.Main registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		8: ASM: class com.stal111.forbidden_arcanus.Main registerContainers(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NoSuchMethodError: net.minecraft.block.FlowerPotBlock.<init>(Lnet/minecraft/block/FlowerPotBlock;Lnet/minecraft/block/Block;Lnet/minecraft/block/Block$Properties;)V
	at com.stal111.forbidden_arcanus.block.ModBlocks.register(ModBlocks.java:225)
	at com.stal111.forbidden_arcanus.Main.registerBlocks(Main.java:56)
	at net.minecraftforge.eventbus.ASMEventHandler_417_Main_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2167/251557282.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2160/2009378486.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2160/2009378486.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
	at net.minecraftforge.fml.ModList$$Lambda$4100/2036265480.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.ModList$$Lambda$2131/1120120878.dispatchEvent(Unknown Source)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:195)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:187)
	at net.minecraftforge.fml.ModLoader$$Lambda$4123/1707947963.accept(Unknown Source)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:187)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:95)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2052/1212094912.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2053/252780183.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:95)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:454)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$401/790689709.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
...
```

I suppose you should report this issue to them.
