### ISSUE TITLE
Server crash: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by Stefanowhb** [Extegral/Enigmatic-Legacy#9]
The server completely crashed when i put an "Eye of the Nebula" in my inventory

Excerpt from latest.log:
```
[13Oct2019 23:39:55.904] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@17c0e3c0 onAdvancement(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.putIfAbsent(Unknown Source)
	at top.theillusivec4.curios.common.capability.CapCurioInventory$CurioInventoryWrapper.lambda$enableCurio$2(CapCurioInventory.java:242)
	at java.util.Optional.ifPresent(Unknown Source)
	at top.theillusivec4.curios.common.capability.CapCurioInventory$CurioInventoryWrapper.enableCurio(CapCurioInventory.java:241)
	at top.theillusivec4.curios.api.CuriosAPI.lambda$enableTypeForEntity$4(CuriosAPI.java:258)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at top.theillusivec4.curios.api.CuriosAPI.enableTypeForEntity(CuriosAPI.java:258)
	at com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler.onAdvancement(EnigmaticEventHandler.java:877)
	at net.minecraftforge.eventbus.ASMEventHandler_73_EnigmaticEventHandler_onAdvancement_AdvancementEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:972)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:204)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35)
	at net.minecraft.advancements.criterion.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:197)
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_192208_a(SourceFile:73)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71111_a(ServerPlayerEntity.java:867)
	at net.minecraft.inventory.container.Container.func_75142_b(Container.java:125)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:321)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Unknown Source)

[13Oct2019 23:39:55.912] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.putIfAbsent(Unknown Source) ~[?:1.8.0_221]
	at top.theillusivec4.curios.common.capability.CapCurioInventory$CurioInventoryWrapper.lambda$enableCurio$2(CapCurioInventory.java:242) ~[?:FORGE-1.14.4-1.0.2.1]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_221]
	at top.theillusivec4.curios.common.capability.CapCurioInventory$CurioInventoryWrapper.enableCurio(CapCurioInventory.java:241) ~[?:FORGE-1.14.4-1.0.2.1]
	at top.theillusivec4.curios.api.CuriosAPI.lambda$enableTypeForEntity$4(CuriosAPI.java:258) ~[?:FORGE-1.14.4-1.0.2.1]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?]
	at top.theillusivec4.curios.api.CuriosAPI.enableTypeForEntity(CuriosAPI.java:258) ~[?:FORGE-1.14.4-1.0.2.1]
	at com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler.onAdvancement(EnigmaticEventHandler.java:877) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_73_EnigmaticEventHandler_onAdvancement_AdvancementEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:972) ~[?:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:204) ~[?:?]
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35) ~[?:?]
	at net.minecraft.advancements.criterion.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:197) ~[?:?]
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_192208_a(SourceFile:73) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71111_a(ServerPlayerEntity.java:867) ~[?:?]
	at net.minecraft.inventory.container.Container.func_75142_b(Container.java:125) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:321) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?]
	... 4 more
```
and the crashlog:
[crash-2019-10-13_23.39.55-server.txt](https://github.com/Extegral/Enigmatic-Legacy/files/3722515/crash-2019-10-13_23.39.55-server.txt)

**Comment by Extegral** [comment]
It appears that the crash happens upon attempt to enable spellstone slot for player, when they receive advancement triggered by obtaning any spellstone. I suspect this originates from Curios, but it will take me some additional testing.

Meanwhile, check if this also happens to you with rings and scrolls. Also, try to fallback to Curious version FORGE-1.14.4-1.0.2, and report whether or not the crash happens in the same conditions then.

**Comment by Extegral** [comment]
I wasn't able to reproduce the issue, but can't see how it could possibly be caused on my side.

So, I guess, you'll have to go to [issue tracker of Curios](https://github.com/TheIllusiveC4/Curios/issues) and report in there.

**Comment by Stefanowhb** [comment]
Sorry for taking so long to get back to you. I can't seem to reproduce it either, even under the exact same circumstances... It doesn't happen to any other advancements either. Odd.

**Comment by Extegral** [comment]
Really odd. In any case, if it happens again - you know what to do.
